### ISSUE TITLE
Bump comp7 to gcc7.5

### ISSUE THREAD

**Issue by timsnyder** [conda-forge/ctng-compilers-feedstock#19]
As I mentioned in #18 , we're running into [a bug in gcc 7.3](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85113)

Would a PR that bumped 7.3 to 7.5 be able to be accepted?

**Comment by isuruf** [comment]
Yes, but `crosstool-ng` has to be updated regardless. See https://github.com/ContinuumIO/crosstool-ng/tree/d158534576f3638bf1d123cdf2c5ea96fa810309/packages/gcc

**Comment by timsnyder** [comment]
Thanks for the pointer @isuruf.  I was trying to remember where all of those patches were.

I see that in the 1.24 conda-forge package for crosstool-ng that it pulled the code out of issuruf/crosstool-ng.  Should we possibly make a conda-forge/crosstool-ng or does that start getting into CFEP territory (maintaining a fork of non cf repo)?

**Comment by isuruf** [comment]
https://github.com/conda-forge/crosstool-ng

**Comment by isuruf** [comment]
@timsnyder, any news on this?

**Comment by timsnyder** [comment]
We were able to get our stuff to build using clang on linux and this became a lower priority for us.  I'd still like to help get gcc bumped to newer but I need to make progress on other things first.

**Comment by isuruf** [comment]
Fixed now
