### ISSUE TITLE
Difference between _openmp_mutex llvm vs gnu?

### ISSUE THREAD

**Issue by jeffwong-nflx** [conda-forge/ctng-compilers-feedstock#20]
On the conda-forge site https://anaconda.org/conda-forge/_openmp_mutex/files

The latest version is 4.5.1, but it's suffixed with llvm. There's an older version 4.5.0 but only for gnu. I have been installing the latest one with llvm, but wondering if I should be using the older one. 

I am compiling a C++ program with gcc and openmp (libgomp) which makes me feel like I should be using 4.5.0_gnu. Is there a reason why gnu does not have a 4.5.1 like llvm? Are you required to compile with clang to use 4.5.1_llvm?

**Comment by timsnyder** [comment]
I think this was fixed in #39 back in August 2020 @jeffwong-nflx.  I hope you got it sorted out.
