### ISSUE TITLE
fix HOST stuff

### ISSUE THREAD

**Issue by beckermr** [conda-forge/ctng-compilers-feedstock#24]
This issue is an xref to https://github.com/AnacondaRecipes/aggregate/pull/172

**Comment by beckermr** [comment]
@timsnyder

**Comment by timsnyder** [comment]
@beckermr I don't know if anyone else ever runs into this or cares but I'm finally coming back around to working on some conda-forge stuff and I could update my PR from the xref'd issue.  Just let me know if you've heard anyone else making noise about it and I'll prioritize.

**Comment by beckermr** [comment]
If you are willing that'd be great!

**Comment by beckermr** [comment]
I thought this would need to be done in the activation feedstock. This issue might be in the wrong place.

**Comment by timsnyder** [comment]
Yeah, it would need to be done in the activation feedstock.  I'll move it over there.

**Comment by timsnyder** [comment]
Moved to https://github.com/conda-forge/ctng-compiler-activation-feedstock/issues/70

**Comment by timsnyder** [comment]
And I guess I'm not allowed to close issues since I'm not a maintainer...

**Comment by beckermr** [comment]
Thank you!
