### ISSUE TITLE
CDT packages don't work

### ISSUE THREAD

**Issue by isuruf** [conda-forge/ctng-compilers-feedstock#28]
The new compilers work fine now, but the CDT packages don't work now.

**Comment by isuruf** [comment]
@beckermr, CDTs end up in `$PREFIX/x86_64-conda_cos6-linux-gnu`, but the compiler only looks at `$PREFIX/x86_64-conda-linux-gnu`

**Comment by beckermr** [comment]
Can you explain?

**Comment by beckermr** [comment]
Ohhhh

**Comment by beckermr** [comment]
Huh?

**Comment by beckermr** [comment]
The tests in them would preclude that.

**Comment by isuruf** [comment]
What do you mean?

**Comment by beckermr** [comment]
We have tests in the sysroot packages that test that the libs are in the right spot on install.

**Comment by isuruf** [comment]
I'm not talking about the libs in the sysroot package. I mean the libs in the CDT packages. For eg: https://anaconda.org/conda-forge/libxt-cos7-ppc64le

**Comment by beckermr** [comment]
Ohhhh crap.

**Comment by beckermr** [comment]
An automated migration for those will be a nightmare.

**Comment by isuruf** [comment]
We don't even build CDTs for x86_64. We just use the ones from defaults.

**Comment by isuruf** [comment]
I hate saying this given the good work you've put into this, but shall we mark the new compilers as broken for a while?

**Comment by beckermr** [comment]
That’s not an option for me. I have colleagues depending on this.

**Comment by isuruf** [comment]
We'll be breaking all recipes using CDTs though.

**Comment by beckermr** [comment]
Not if we put in symlinks that replicate the old sysroot. We now have an excellent reason to keep the old ones.

**Comment by isuruf** [comment]
How is that going to work?

**Comment by beckermr** [comment]
What do you mean? We adjust the linux sysroot packages to use the old sysroot names and then add a symlink to the new one.

**Comment by isuruf** [comment]
Do you mean `2.17` would also be in `cos6`?

**Comment by beckermr** [comment]
Yep why not. It is just a directory name. Actually pulling cos7 CDTs is a much bigger issue that I don't think we can solve.

**Comment by isuruf** [comment]
Can you send a PR to fix sysroot_linux-64=2.12? I think that should be enough to solve the issues.

If we build the compilers with `sysroot_linux` with no `conda_cos6` folders as we have already done, the index.json will have `conda` files only. Then, we can actually have `sysroot_linux-64=2.17` with `conda_cos7` and cos7 CDTs.

**Comment by beckermr** [comment]
Just to be clear, we’ll need symlinks from the compiler shim sysroot to the current one. 

Also, should we be worried about mixing cdts between cos6 and cos7? Do we need to put in run constraints on say the sysroot package or some sort of centos cdt mutex?

**Comment by isuruf** [comment]
> Just to be clear, we’ll need symlinks from the compiler shim sysroot to the current one.

Yes, we need to move the sysroot_linux-64's files to `conda_cos6` and add a symlink, `conda->conda_cos6`.

> Also, should we be worried about mixing cdts between cos6 and cos7?

Not at the moment.

**Comment by beckermr** [comment]
Ok if we are not worried about mixing cdts then I propose we stuff the cos7 sysroot in the cos6 path too. Otherwise people who use cos7 won’t have any CDTs at all.

**Comment by isuruf** [comment]
> Otherwise people who use cos7 won’t have any CDTs at all.

What I mean is it's bad to mix CDTs, but we shouldn't worry about a mutex for now since we don't have any cos7 CDTs. 

People who want to use cos7 should build CDTs for cos7.

**Comment by beckermr** [comment]
Hmm ok. I’d be nice to have an answer for automatically generating the cdt packages.

**Comment by beckermr** [comment]
Also we should have a story on a mutex before we ask ppl to build cdts

**Comment by isuruf** [comment]
If you use `conda-build`, there's a kind of mutex because `{{ cdt('foo') }}` will be expanded to `foo_{{ cdt_name }}_{{ cdt_arch }}` and `cdt_name` is constant for a given run

**Comment by beckermr** [comment]
Ah so we can set cdt name then. Sounds good.

**Comment by beckermr** [comment]
Should we rename the kernel headers and sysroot packages to use the cdt jinja2 in order to make them be able to be selected by the same logic?

**Comment by isuruf** [comment]
What would the run requirement for the compiler be then?

**Comment by beckermr** [comment]
We could / should insert shim cdts for the sysroot that people can insert into the build section. These cdts would simply have a run dep on the correct sysroot version. The actual compiler packages would stay the same. This way people can make sure to use the same cdt version as they have for the libraries in the host section. Also, for cross compiling people can specify the sysroot they want by name / version instead of cdt.

**Comment by s22chan** [comment]
For the time being, can you remove the `main` label from

 linux-64/gxx_impl_linux-64-7.5.0-h64c220c_7 and  linux-64/gxx_impl_linux-64-7.5.0-h64c220c_8

packages since this is breaking builds clang builds that rely on CONDA_BUILD_SYSROOT being defined correctly by the compiler activation script.

**Comment by beckermr** [comment]
I’m about to go to bed. We will fix this tomorrow morning for sure.

**Comment by beckermr** [comment]
I’d you can send a pr to cf mark broken in the next 5 mins or so I can merge it.

**Comment by s22chan** [comment]
you do that via anaconda.org or the CLI: https://docs.anaconda.com/anaconda-cloud/user-guide/tutorials/

see move labels

**Comment by isuruf** [comment]
@s22chan, we use https://github.com/conda-forge/cf-mark-broken for it. Can you send a PR?

**Comment by s22chan** [comment]
@isuruf this tool doesn't work (to remove a broken build from being in the conda solution set), since it only adds a broken label, but doesn't remove the main label

**Comment by s22chan** [comment]
you can see that most of the sysroot packages and gxx_impl packages have both main and broken labels

**Comment by beckermr** [comment]
see here: https://github.com/conda-forge/linux-sysroot-feedstock/pull/18

**Comment by beckermr** [comment]
see here too: https://github.com/conda-forge/linux-sysroot-feedstock/pull/19

**Comment by beckermr** [comment]
closing this one since the sysroot paths are now fixed!
